# Generated by Django 2.2 on 2022-09-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201105_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('HONDA', 'HONDA'), ('MITSUBISHI', 'MITSUBISHI'), ('NISSAN', 'NISSAN'), ('HYUNDAI', 'HYUNDAI'), ('KIA', 'KIA'), ('SUZUKI', 'SUZUKI'), ('TOYOTA', 'TOYOTA')], default='Other', max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
